# wordfreak: word frequency counter over POSIX open/read/write/close.
#
# Targets (the contract in docs/conventions.md section 3):
#   all    (default) release build into build/wordfreak
#   debug  -O0 -g3 build into build/debug/wordfreak
#   test   build, then run every unit and end-to-end test
#   check  gcc -fanalyzer over every source file in src/
#   run    build, then run the program on the sample texts
#   dist   flat Gradescope bundle in dist/, proven to build
#   clean  remove build/, dist/ and output.txt

# The compiler can be overridden: make CC=clang. GNU make predefines CC=cc,
# so `CC ?= gcc` would never take effect; only make's own default is replaced.
ifeq ($(origin CC),default)
CC = gcc
endif

# Language level. The spec's course machine builds with gcc -std=c99, and
# open/read/write/close are POSIX, which strict C99 hides without the
# feature-test macro.
STD_FLAGS := -std=c99 -D_POSIX_C_SOURCE=200809L

# The mandatory warning set; every warning is an error in the dev build.
WARN_FLAGS := -Wall -Wextra -Wpedantic -Wshadow -Wstrict-prototypes \
              -Wmissing-prototypes -Wconversion -Wvla -Werror

# Optimisation for the release build; a reviewer may override CFLAGS.
CFLAGS ?= -O2
DEBUG_CFLAGS := -O0 -g3
LDFLAGS ?=

# -MMD -MP writes a .d file per object so header edits trigger rebuilds.
DEP_FLAGS := -MMD -MP

SRC_DIR := src
BUILD_DIR := build
DEBUG_DIR := $(BUILD_DIR)/debug
DIST_DIR := dist
PROGRAM := wordfreak

SOURCES := $(wildcard $(SRC_DIR)/*.c)
HEADERS := $(wildcard $(SRC_DIR)/*.h)
OBJECTS := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SOURCES))
DEBUG_OBJECTS := $(patsubst $(SRC_DIR)/%.c,$(DEBUG_DIR)/%.o,$(SOURCES))

# Sample inputs the run target and the e2e tests share.
SAMPLES := test/e2e/cases/fable.txt test/e2e/cases/second.txt

.PHONY: all debug test check run dist clean

all: $(BUILD_DIR)/$(PROGRAM)

debug: $(DEBUG_DIR)/$(PROGRAM)

# Release objects and binary. Objects never land next to the sources.
$(BUILD_DIR)/$(PROGRAM): $(OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $^

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(STD_FLAGS) $(WARN_FLAGS) $(CFLAGS) $(DEP_FLAGS) -c -o $@ $<

# Debug objects and binary live in their own directory so the two builds
# never share stale objects.
$(DEBUG_DIR)/$(PROGRAM): $(DEBUG_OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $^

$(DEBUG_DIR)/%.o: $(SRC_DIR)/%.c | $(DEBUG_DIR)
	$(CC) $(STD_FLAGS) $(WARN_FLAGS) $(DEBUG_CFLAGS) $(DEP_FLAGS) -c -o $@ $<

$(BUILD_DIR) $(DEBUG_DIR):
	mkdir -p $@

# The test runner compiles the unit tests itself with the flags exported
# here, so the tests face the same warning set as the sources.
test: all
	CC="$(CC)" TEST_CFLAGS="$(STD_FLAGS) $(WARN_FLAGS) $(DEBUG_CFLAGS)" \
	    ./test/run_tests.sh

# Static analysis; the build is only considered clean when this is silent.
check:
	$(CC) $(STD_FLAGS) $(WARN_FLAGS) -fanalyzer -fsyntax-only $(SOURCES)

# Runs the program the way the spec's examples do: stdin plus argument files.
run: all
	echo "" | ./$(BUILD_DIR)/$(PROGRAM) $(SAMPLES)
	cat output.txt

# The flat bundle Gradescope wants: sources, headers, README and a Makefile
# that builds in place. The bundle is built once to prove it compiles.
dist: $(SOURCES) $(HEADERS) README.txt
	rm -rf $(DIST_DIR)
	mkdir -p $(DIST_DIR)
	cp $(SOURCES) $(HEADERS) README.txt $(DIST_DIR)/
	printf '%s\n' \
	    '# wordfreak: builds the executable "wordfreak" in place.' \
	    '# GNU make predefines CC=cc, so only its default is replaced by gcc.' \
	    'ifeq ($$(origin CC),default)' \
	    'CC = gcc' \
	    'endif' \
	    'CFLAGS ?= -std=c99 -D_POSIX_C_SOURCE=200809L -O2 -Wall -Wextra -Wpedantic' \
	    'SOURCES := $$(wildcard *.c)' \
	    'OBJECTS := $$(SOURCES:.c=.o)' \
	    '' \
	    '.PHONY: all clean' \
	    '' \
	    'all: $(PROGRAM)' \
	    '' \
	    '$(PROGRAM): $$(OBJECTS)' \
	    '	$$(CC) $$(CFLAGS) -o $$@ $$^' \
	    '' \
	    '%.o: %.c $$(wildcard *.h)' \
	    '	$$(CC) $$(CFLAGS) -c -o $$@ $$<' \
	    '' \
	    'clean:' \
	    '	rm -f $$(OBJECTS) $(PROGRAM) output.txt' \
	    > $(DIST_DIR)/Makefile
	$(MAKE) -C $(DIST_DIR)
	ls -l $(DIST_DIR)/$(PROGRAM)

clean:
	rm -rf $(BUILD_DIR) $(DIST_DIR) output.txt

# Header dependency files generated by -MMD; absent on a fresh checkout.
-include $(OBJECTS:.o=.d) $(DEBUG_OBJECTS:.o=.d)
